site_name: OntoMutate
nav:
    - Home: index.md
    - Installation: installation.md
    - Basic Usage: basicUsage.md
    - Tool Parameters: parameters.md
    - Mask Specification: mask.md
    - Mutation Specification: mutationOperator.md
    - Tutorial: tutorial.md
    - About: about.md
theme: readthedocs
