strict_parsing: true
print_summary: false

seed_graph:
    file: <seed-file-name>
    type: owl
    
output_graph:
    file: <outputFile>
    overwrite: true 
    type.: rdf
    
number_of_mutations: 5

strategy:
    name: random
    seed: 42
	
condition:
    reasoning:
        consistency: true
        reasoner: hermit 
    masks:
        - file: <shaclFilePath>
        - file: <anotherShaclFilePath>
        
        
mutation_operators:
    - module:
        location: org.smolang.robust.mutant.DefinedMutants
        operators: 
            - className: <class name>
            - className: <another class name>
    - resource:
        file: <sadf>
        syntax: swrl
        


